### ISSUE TITLE
Using pythonnet with Unity3D

### ISSUE THREAD

**Issue by HuangJunye** [Cerberus1746/PandaCoreData#4]
Hi @Cerberus1746 ! Thank you for sharing your tutorial on how to get pythonnet working with Unity3D https://github.com/Cerberus1746/PandaCoreData/blob/master/docs/source/tutorial/unity.rst This is the best one I have found on the internet. However, when I tried to follow the steps, Unity crashes every time when I click the run button. Do you have any idea how to solve the problem?

This is a similar issue I have found which doesn't provide any solution: https://github.com/pythonnet/pythonnet/issues/699

**Comment by leandro-benedet-garcia** [comment]
@HuangJunye What's the version of python, unity, .net and etc are you using?

Also, Did you install anything with nuget?

**Comment by HuangJunye** [comment]
Thanks for the reply! I am using python 3.7.3, unity 2019.2.2f1, not sure about .NET version. I'll check.

No, I didn't install anything using nuget. I have done only the steps you mentioned in the tutorial.
